version: '3.8'

services:
  postgres_dev:
    image: postgres:13
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  alembic:
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres_dev
      - postgres_test
    command: >
      sh -c "pip install -r requirements.txt &&
             alembic upgrade head"

volumes:
  postgres_dev_data:
  postgres_test_data: