running:
  run_web_server: true
  run_background_jobs: true

  # prod/test  -> local_development: false
  local_development: true
  # prod/test  -> debug: false
  debug: true

config:
  # generic config
  log_level: "INFO"
  sentry_url: "https://{your_project_hash}@sentry.com/{project_id}?verify_ssl=0"

database:
  connection: "postgresql://dev_user:dev_password@localhost:5432/dev_db"

no_sql_database:
  connection: "mongodb://dev_user:dev_password@mongodb:27017/dev_db"


web_server:
  port: 8080
  host: 0.0.0.0 
  swagger_relative_path: "/"

background_jobs:
  name: "sensor_app"
  broker: "redis://localhost:6379/0"
  backend: "db+postgresql://dev_user:dev_password@localhost:5432/dev_db"
  task_always_eager: false
  task_eager_propagates: false
  admin_dashboard_user: "user"
  admin_dashboard_user_password: "password"
